### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Mandino16** [AncientCreaturesDeveliper/Ancient-Creatures#2]
The computer texture does not work.

**Comment by AncientCreaturesDeveliper** [comment]
Please, attach a screenshot so I can see the issue because my testing didn't show any issues. If you can do that I'll be able to help! :)

**Comment by Mandino16** [comment]
![Bug](https://user-images.githubusercontent.com/67841041/86976771-37bb0c00-c149-11ea-9a72-4573f855a89b.png)

**Comment by AncientCreaturesDeveliper** [comment]
How often does this happen? Does it happen every time? Or just in this configuration?

**Comment by Mandino16** [comment]
I opened up a new world with this mod and jei installed and texture still does not work. If it helps, i am using twitch. Probably doesn't make a difference.

**Comment by AncientCreaturesDeveliper** [comment]
I dont think that Twitch would make a difference. If anything might help, look in the mod file with something like 7-ZIP or WinRAR and in the files, go to source/main/resources/assets/ancientcreatures/blockstates. There, you will find tons of files, simply look for Computer.json and make sure that is in there. If it is in there, then i'd try installing Optifine, sometimes it could help. Otherwise, I'm not sure about that. If you do try Optifine, go to https://optifine.net/downloads click on Preview Releases and download OptiFine 1.15.2 HD U G1 pre30. Don't worry, it's completely free. I hope this helps! :)
